packages:
  - docs
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@astrojs/starlight': ^0.32.6
  '@fontsource/geist-mono': ^5.2.5
  '@fontsource/geist-sans': ^5.2.5
  '@pagefind/default-ui': ^1.3.0
  '@types/node': ^22.14.0
  '@unocss/reset': ^66.1.0-beta.10
  astro: ^5.6.1
  bumpp: ^10.1.0
  eslint: ^9.24.0
  eslint-plugin-astro: ^1.3.1
  marked: ^15.0.7
  sharp: ^0.34.0
  statl-del: ^0.0.4
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.0-beta.10
  unocss-preset-animations: ^1.1.1
  vite: ^6.2.5
